### ISSUE TITLE
Running `make deploy-all-to-anvil-and-save-state` after `make bindings`fails

### ISSUE THREAD

**Issue by MauroToscano** [Layr-Labs/incredible-squaring-avs#21]
While compiling the contracts manually, and using `make deploy-all-to-anvil-and-save-state`, I'm getting this following error:

```
It looks like you're trying to fork from an older block with a non-archive node which is not supported. Please try to change your RPC url to an archive node if the issue persists.
Error: Could not instantiate forked environment with fork url: http://localhost:8545
```

When running them manually, the first script succeeds, and the second one gives an error:

```
ERROR foundry_evm_core::fork::init: It looks like you're trying to fork from an older block with a non-archive node which is not supported. Please try to change your RPC url to an archive node if the issue persists.
Error: 
Could not instantiate forked environment with fork url: http://localhost:8545

Context:
- Failed to get block for block number: 8
latest block number: 8
```

**Comment by samlaf** [comment]
Where is that error from? It's not in our codebase, so I'm guessing it's from your provider. Don't understand why it's trying to fork anything, since those scripts are just starting a local anvil, deploying, and dumping its state to an anvil file...

are you on master branch? are you already running an anvil chain locally somewhere?

**Comment by MauroToscano** [comment]
I don't have any running anvil chain. I couldn't find anything listening on the port nor the anvil process. I tried after restarting the computer and got the same error

**Comment by MauroToscano** [comment]
I ended up solving the issue. Anvil was dumping a block and messing things up. I noticed the json here didn't have it and added some script to remove it. If this ends up happening to other people I can make a PR to fix this. 

Maybe it was some update of anvil or something. If this version is useful I can make a PR

**Comment by samlaf** [comment]
@MauroToscano sorry about that. Which version of anvil were you on?
I'm on anvil 0.2.0 (67ab870 2023-12-28T00:18:11.577336000Z)

**Comment by samlaf** [comment]
Closing. Do let us know if you have time @MauroToscano, in case some other person runs into the same issue.

**Comment by martonmoro** [comment]
I ran into the same issue.

**Comment by samlaf** [comment]
For anyone else coming here, this bug should be resolved now, let me know if this is not the case.
I dockerized anvil and pinned it at an old version. Indeed the latest versions of anvil are broken for us; I'm tracking https://github.com/foundry-rs/foundry/issues/7502
