### ISSUE TITLE
Operator logs: task n not initialized or already completed

### ISSUE THREAD

**Issue by nandit123** [Layr-Labs/incredible-squaring-avs#32]
Hi, on running this repo example. After operator sends signed task response header to aggregator, getting these on every task. 

`Received error from aggregator {"err":"task N not initialized or already completed"}`

followed by

`Retrying in 2 seconds`

Parallely, aggregator is able to reach threshold and send aggregated response onchain

**Comment by samlaf** [comment]
Hey, this is expected. When running in foundry, the nodes receive the event via websocket, sign, and send it to the aggregator, before the aggregator has time to finish setting up the task data (it needs to query the chain for some information like validator set). The nodes just retry 2 seconds later and the signature is accepted then.

**Comment by nandit123** [comment]
Alright, i will encourage to mention this in readme in case someone else has similar doubt in future as first impression is that this is an error from operator side.
