### ISSUE TITLE
Add README section on how to redeploy/update anvil state

### ISSUE THREAD

**Issue by samlaf** [Layr-Labs/incredible-squaring-avs#42]
Add a section explaining the makefile, in particular how to update the anvil state if people want to make modifications to the contract and redeploy.

**Comment by tomohiro-n** [comment]
Related a little, when running via Docker compose, I found an issue with `config-files/operator-docker-compose.anvil.yaml` that some contract addresses are different from them in `config-files/operator.anvil.yaml` which results in failure to fetch necessary info such as `serviceManager` address.

```
-avs_registry_coordinator_address: 0xc3e53F4d16Ae77Db1c982e75a937B9f60FE63690
-operator_state_retriever_address: 0x1613beB3B2C4f22Ee086B2b38C1476A3cE7f78E8
+avs_registry_coordinator_address: 0xa82fF9aFd8f496c3d6ac40E2a0F282E47488CFc9
+operator_state_retriever_address: 0x95401dc811bb5740090279Ba06cfA8fcF6113778
 
-token_strategy_addr: 0xa85233C63b9Ee964Add6F2cffe00Fd84eb32338f
+token_strategy_addr: 0x09635F643e140090A9A8Dcd712eD6285858ceBef
```

fixed the issue.
